@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User")
Container(PostService, "Post service", "Software system", "CRUD for posts, comments and likes")
Container(FollowingService, "Following service", "Software system", "Stores relation info")
Container(MediaService, "Media service", "S3 storage", "Stores media files")
Container(GeoService, "Geo service", "Software system", "Stores Geo data")
Container(FeedService, "Feed service", "Software system", "Work with cached feed")
Container(CDN, "CDN", "CloudFlare", "Location based CDN")

Rel(user, GeoService, "Add/get geo locations")
Rel(user, PostService, "CRUD")
Rel(user, FollowingService, "Subscribe or unsubscribe")
Rel(user, FeedService, "Get feed")
Rel(user, CDN, "Get media")
Rel(CDN, MediaService, "Put/get media")
@enduml