@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User")
Container(ApiGateway, "API Gateway", "Nginx", "Round robin balancer")
ContainerQueue(MessageQueue, "Events queue", "Kafka", "Common event bus for any domain event")
Container(PostService, "Post Service", "Go", "Posts CRUD", $tags="webApp")
Container(FollowingService, "Following service", "Software system", "Stores relation info")
Container(CDN, "CDN", "CloudFlare", "Location based CDN")


System_Boundary(FeedSystem, "Feed System") {
    Container(FeedService, "Feed Service", "Go", "Stores a cache for quick response to the user", $tags="webApp")
    ContainerDb(FeedCache, "Feed cache", "Redis", "Stores a cache")
    ContainerDb(FeedDB, "Feed DB", "Postgres", "Stores a feeds")
}

Rel(user, ApiGateway, "Get feeds", "REST")
Rel(FeedService, MessageQueue, "Consume posts events to prepare cache feed")
Rel(FeedService, FeedCache, "Set/Get prepared view, if no data, it would going to cold storage")
Rel(FeedService, FeedDB, "Cold storage for old feedings")
Rel(user, CDN, "Get media for feed")
Rel(PostService, MessageQueue, "Produce posts events")
Rel(FollowingService, MessageQueue, "Produce following events")
Rel(ApiGateway, FeedService, "CRUD posts")

@enduml
